### ISSUE TITLE
How to make it work automatically with .proto3? 

### ISSUE THREAD

**Issue by Carglass** [VcamX/protobuf-syntax-highlighting#2]
Hi,

The package is working pretty well with .proto files, however, recently my colleagues updated our protobuf to .proto3. I can still activate manually the package for each file, and it works, but is there a way to have it detect .proto3 files when i open them? 

Thanks

**Comment by frou** [comment]
What about the Sublime menu item `View > Syntax > Open all with current extension as...` ?

**Comment by Carglass** [comment]
It works for each session indeed. Thanks for the tip, I did not know the option.

**Comment by gwenzek** [comment]
By default this syntax only triggers for the standard extensions ".proto" and ".protodevel".
".proto3" isn't a very common extension, as far as I know.
